{
 "title": "Janani",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Departments",
    "query": "SELECT DISTINCT department_name FROM janani\n"
   }
  ]
 },
 "panels": [
  {
   "title": "TOTAL STUDENTS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT SUM(CAST(Total_Students AS INTEGER)) FROM janani;\r\n"
    }
   ]
  },
  {
   "title": "INSTITUTIONAL RETURN ON INVESTMENT (ROI)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT AVG(CAST(Institutional_ROI AS FLOAT)) AS avg_roi FROM janani;\r\n"
    }
   ]
  },
  {
   "title": "AVERAGE DEPARTMENTAL PERFORMANCE INDEX (DPI)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT AVG(CAST(Departmental_Performance_Index_DPI AS FLOAT)) AS avg_dpi FROM janani;\r\n"
    }
   ]
  },
  {
   "title": "TOTAL OFFERS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT SUM(CAST(Total_Offers AS INTEGER)) FROM janani;\r\n"
    }
   ]
  },
  {
   "title": "ACTIVE PARTICIPANTS BY DEPARTMENT",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT Department_Name,\r\n       SUM(CAST(Active_Participants AS INTEGER)) AS total_active_participants\r\nFROM janani\r\nGROUP BY Department_Name\r\nORDER BY total_active_participants DESC;\r\n"
    }
   ]
  },
  {
   "title": "YEAR-WISE STUDENT AND OFFER TRENDS",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT Event_Year,\r\n       SUM(CAST(Total_Students AS INTEGER)) AS total_students,\r\n       SUM(CAST(Total_Offers AS INTEGER)) AS total_offers\r\nFROM janani\r\nGROUP BY Event_Year\r\nORDER BY Event_Year;\r\n"
    }
   ]
  },
  {
   "title": "PLACEMENT SUCCESS RATE BY DEPARTMENT AND YEAR",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  Department_Name,\r\n  Event_Year,\r\n  SUM(CAST(Total_Students AS INTEGER)) AS students,\r\n  SUM(CAST(Total_Offers AS INTEGER)) AS offers,\r\n  ROUND(\r\n    ((SUM(CAST(Total_Offers AS INTEGER))::FLOAT / NULLIF(SUM(CAST(Total_Students AS INTEGER)), 0)) * 100)::numeric,\r\n    2\r\n  ) AS placement_success_rate_percentage\r\nFROM janani\r\nGROUP BY Department_Name, Event_Year\r\nORDER BY Event_Year, Department_Name;\r\n"
    }
   ]
  },
  {
   "title": "TOTAL FACULTY & ACTIVE MENTORS BY DEPARTMENT",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT Department_Name,\r\n       SUM(CAST(Total_Faculty AS INTEGER)) AS total_faculty,\r\n       SUM(CAST(Active_Mentors AS INTEGER)) AS total_active_mentors\r\nFROM janani\r\nGROUP BY Department_Name\r\nORDER BY total_faculty DESC;\r\n"
    }
   ]
  },
  {
   "title": "AVERAGE INNOVATION SCORE BY DEPARTMENT",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT Department_Name,\r\n       AVG(CAST(Innovation_Score_Avg AS FLOAT)) AS avg_innovation_score\r\nFROM janani\r\nGROUP BY Department_Name\r\nORDER BY avg_innovation_score DESC;\r\n"
    }
   ]
  },
  {
   "title": "TOP 5 DEPARTMENTS: STUDENTS & OFFERS COMPARISON",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT Department_Name,\r\n       SUM(CAST(Total_Students AS INTEGER)) AS total_students,\r\n       SUM(CAST(Total_Offers AS INTEGER)) AS total_offers\r\nFROM janani\r\nGROUP BY Department_Name\r\nORDER BY total_students DESC\r\nLIMIT 5;\r\n"
    }
   ]
  },
  {
   "title": "INDUSTRY ENGAGEMENT BY DEPARTMENT: RECRUITER VISITS & PARTNERSHIPS",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT department_name,\r\n       SUM(CAST(recruiter_visits AS INTEGER)) AS total_recruiter_visits,\r\n       SUM(CAST(partnership_count AS INTEGER)) AS total_partnerships\r\nFROM janani\r\nGROUP BY department_name\r\nORDER BY total_recruiter_visits DESC;\r\n"
    }
   ]
  },
  {
   "title": " RECRUITER VISITS BY DEPARTMENT",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT Department_Name,\r\n       SUM(CAST(Recruiter_Visits AS INTEGER)) AS total_recruiter_visits\r\nFROM janani\r\nGROUP BY Department_Name\r\nORDER BY total_recruiter_visits DESC;\r\n"
    }
   ]
  },
  {
   "title": "DISTRIBUTION OF ACTIVE PARTICIPANTS BY DEPARTMENT",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT department_name,\r\n       SUM(CAST(active_participants AS INTEGER)) AS total_active_participants\r\nFROM janani\r\nGROUP BY department_name\r\nORDER BY total_active_participants DESC;\r\n"
    }
   ]
  },
  {
   "title": "HACKATHON INVESTMENT VS. INNOVATION SCORE BY DEPARTMENT",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    department_name,\r\n    SUM(CAST(total_hackathon_cost AS FLOAT)) AS total_hackathon_cost,\r\n    ROUND(AVG(CAST(innovation_score_avg AS FLOAT))::numeric, 3) AS avg_innovation_score\r\nFROM janani\r\nGROUP BY department_name\r\nORDER BY total_hackathon_cost DESC;\r\n"
    }
   ]
  }
 ]
}